import type { Metadata } from "next";
import "../globals.css";
import { logout } from "@/actions/auth-action";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header id="auth-header">
            <p>Welcome back!</p>
            <form action={logout}>
                <button>Logout</button>
            </form>
        </header>
        {children}
      </body>
    </html>
  );
}
